### ISSUE TITLE
'Unsupported msg type'

### ISSUE THREAD

**Issue by meanmee** [yl-1993/hfsoftmax#3]
def _recv(self):
        # TODO: 
        #   1. use logging to better log server info
        #   2. better exception handling
        print('waiting for message ... ')
        packet = self._socket.recv_multipart()
        print(packet)
        print(len(packet))
        if len(packet) == 2:
            ident, msg = packet
            msg = self._parse_json(msg)
        elif len(packet) == 4:
            ident, msg, meta, data = packet
            msg, meta = map(self._parse_json, [msg, meta])
            if msg['op'] == 'set_matrix':
                msg['data'] = self._buf_to_ndarray(data, meta)
            else:
                msg['rows'] = self._buf_to_ndarray(data, meta)
        elif len(packet) == 6:
            ident, msg, rows_meta, rows_data, val_meta, val_data = packet
            msg, rows_meta, val_meta = map(self._parse_json, [msg, rows_meta, val_meta])
            msg['rows'] = self._buf_to_ndarray(rows_data, rows_meta)
            msg['data'] = self._buf_to_ndarray(val_data, val_meta)
        else:
            raise RuntimeError('Unsupported msg type')
        self.handle(ident, msg)

always raise an error: RuntimeError('Unsupported msg type')
I find where the error shows up, but don't why?

**Comment by meanmee** [comment]
I find out the len(packet) is 10 when the error shows up

**Comment by meanmee** [comment]
Seems like it is because i change one gpu to 4 gpus for training, One gpu is Okay. How to make it possible training hf softmax with 8 gpus in one machine?

**Comment by yl-1993** [comment]
@meanmee Can you post more detailed about your multi-gpus setting? Besides,
1. You can refer to [the guidelines for distributed hf](https://github.com/yl-1993/hfsoftmax#distributed-training) first.
2. The launch script of multi-gpus has some minor difference with one gpu. Check [this folder](https://github.com/yl-1993/hfsoftmax/tree/master/scripts) for more details.
