### ISSUE TITLE
‘get_value_by_rows’ Fall into an infinite loop

### ISSUE THREAD

**Issue by alan525** [yl-1993/hfsoftmax#4]
Hi， It's a great work. When I am using the sampling layer（hnsw_sampler.py）, the program runs to 'update_hf ' function, falls into an infinite loop in 'get_value_by_rows', and cannot enter the conditional judgment. Part of the code is as follows：
#####################################################
while True:
            sockets = dict(self._poll.poll(1000))
            if self._socket in sockets:
                msg = self._socket.recv()
                if not meta:
                    meta = json.loads(msg)
                else:
                    data = np.frombuffer(msg, dtype=meta['dtype'])
                    return data.reshape(meta['shape'])
#####################################################

**Comment by alan525** [comment]
In the code running, 'sockets' is always an empty dictionary.

**Comment by yl-1993** [comment]
Hi Alan@alan525 , have you launched the parameter server before starting the training?
You can try to launch the parameter server first as follows.
```python paramserver/paramserver.py```

**Comment by alan525** [comment]
Yes, I missed this key message, thank you very much.

**Comment by yl-1993** [comment]
Thanks for trying the code. Maybe a warning message should be alerted if the parameter server is not detected.
