### ISSUE TITLE
Problems about the training

### ISSUE THREAD

**Issue by wjxzju** [yl-1993/hfsoftmax#7]
Hi, I have two problems about the hfsoftmax
1. The sampler works from the beginning of training process, while the CPk (for example, top 1000) is very low at the beginning,  how to ensure it works? 
2. The adaptive allocation scheme not release the code ?  only see sample_num=1000,

**Comment by yl-1993** [comment]
Hi @wjxzju 
1. I guess your concern is applying samplers in the early stage will harm the training process. Actually, at the beginning of the training, the sampler randomly selects some classes for feature learning. As the training proceeds, the feature becomes more distinguishable and the sampler can also be more efficient to identify active classes.
2. Yes. We have not released adaptive allocation yet.
