### ISSUE TITLE
about Feature Extraction

### ISSUE THREAD

**Issue by Linsongrong** [yl-1993/hfsoftmax#9]
Hello, I am a beginner, trying to extract features, can you tell me what the three parameters prefix, filelist, load_path mean?

**Comment by yl-1993** [comment]
@Linsongrong Hi, thanks for the question.
- `prefix`: the image prefix of storing images, e.g., /mnt/DATA/
- `filelist`: the list of image filename, e.g., 0/0.jpg, 0/10.jpg, 1/5.jpg. We can access an image by concatenating `prefix` and its `filename`.
- `load_path`: the path of a pretrained checkpoint

Feel free to keep posting issues if anything is unclear. A more detailed doc will be provided in the future.

**Comment by Linsongrong** [comment]
thanks
